### ISSUE TITLE
exception while running cucumber test runner as Junit

### ISSUE THREAD

**Issue by ank1006** [cucumber/common#2147]
I keep running into following exceptions while executing cucumber test runner file as Junit-
java.lang.NoClassDefFoundError: org/junit/runner/manipulation/Filter
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.loadTestLoaderClass(RemoteTestRunner.java:380)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.createRawTestLoader(RemoteTestRunner.java:370)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.createLoader(RemoteTestRunner.java:365)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.defaultInit(RemoteTestRunner.java:309)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.init(RemoteTestRunner.java:224)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:208)
Caused by: java.lang.ClassNotFoundException: org.junit.runner.manipulation.Filter
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 8 more

Referenced Libraries-
![image](https://user-images.githubusercontent.com/47805449/221069061-f2e1737c-3b72-4d6a-be5c-c6e3edf83e7d.png)

**Comment by mpkorstanje** [comment]
I don't see Cucumber in that stacktrace. So probably a problem with Eclipse. Did you see this problem on Stackoverflow?

https://stackoverflow.com/questions/33521436/junit-noclassdeffounderror-org-junit-runner-manipulation-filter

**Comment by ank1006** [comment]
yep, saw that but surprisingly i don't see ModulePath and Classpath within libraries tab when i navigate to Java Build Path. Within libraries i directly see dependencies i added, JRE System Library and the Junit 4.
I just updated package names, restarted eclipse and now on running i am seeing following exception-

java.lang.NullPointerException
	at java.time.Duration.between(Unknown Source)
	at io.cucumber.core.runtime.CucumberExecutionContext.emitTestRunFinished(CucumberExecutionContext.java:129)
	at io.cucumber.core.runtime.CucumberExecutionContext.finishTestRun(CucumberExecutionContext.java:118)
	at io.cucumber.junit.Cucumber$FinishTestRun.evaluate(Cucumber.java:250)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
